branches:
  except:
    - gh-pages

language: cpp

compiler:
  - gcc

before_deploy:
  - echo test > a.txt
  
deploy:
  provider: releases
  api-key:
    secure: "ZRv48EPB9lI2Iugzi8H0CcDEmEEXzAWMBBh6LZNPfTsDVQQdr8/1NgUvCOqA5a7uEIQv38H2UwgQSpGKiwEBJ5eP4VugOUK90G4HoteaadTe/ARTCIgPjpfYF0UT5M5ijkoxLIZeytYyI5yuBvy21gc6FG6oXdWbExmlbjNMXeQ="
  file: "a.txt"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    
install:
  - "echo install"

script:
  - "echo script"
